### ISSUE TITLE
MarkupsToModel auto update checkbox on makes using the module error-prone

### ISSUE THREAD

**Issue by cpinter** [SlicerIGT/SlicerIGT#92]
It's quite unexpected (and unprecedented in Slicer) that simply switching to a module initiates processing. 
Also I lost data by removing the automatically created model while auto-update was still on.
I think it would be better if the auto-update combobox was off by default.

**Comment by lassoan** [comment]
@tavaughan has been working on a complete GUI rework - it's almost-ready for integration (https://github.com/SlicerIGT/SlicerIGT/pull/90). We should test the behavior again after his changes have been integrated.

Probably the issue is that "None" option is not enabled in the output node selector and so it selects the first model node in the scene.

**Comment by cpinter** [comment]
OK thanks! I wasn't aware of the UI rework.

Why is auto-update on by default? I think the problem is not (only) the None option, but more the auto-update, as I suggest in the ticket title.

**Comment by lassoan** [comment]
Auto-update is good, because that's what you need most of the time. Auto-update is enabled by default in Fiducial registration wizard, too, and nobody complained. The problem is that the module randomly selects a node as you enter the module and you don't have a chance to turn off auto-update or choose a different output node.

**Comment by cpinter** [comment]
Adding the None options would help for sure.

I think it is very unusual in Slicer that by changing selection in a node combobox immediately changes the content of the node without explicit action (may it be enabling auto-update or clicking manual update). I didn't see any module operating like this before outside SlicerIGT.

**Comment by lassoan** [comment]
Yes, SlicerIGT is "unusual" because it mainly operates on nodes that are changing in real-time, that's why auto-update is the default for most modules (but it can be disabled for a few modules such as for this one).

**Comment by cpinter** [comment]
If for SlicerIGT's use cases this "real-time behaviour" is better, and it is accepted that the modules in the extension don't work the same way as Slicer core, then auto-update is fine by me.

In this case adding None to the output combobox is enough.

**Comment by tavaughan** [comment]
The GUI update will address this issue by allowing "None" in the output combobox.

**Comment by tavaughan** [comment]
(And "None" will be selected by default)

**Comment by tavaughan** [comment]
Should this be closed?

**Comment by cpinter** [comment]
Has the above discussed None option been added?

**Comment by tavaughan** [comment]
It was merged in this commit:
https://github.com/SlicerIGT/SlicerIGT/commit/c14531826551f9c0e6ae8e7a5aabaa64bc83ae95

**Comment by cpinter** [comment]
Thanks! In that case I think this issue can be closed. I'm closing it now.
